GET http://localhost:8000/user/login




###
POST  http://localhost:8000/user/register
content-type: application/json

{
    "email": "copycat@gmail.com",
    "password": "123"
}


###
POST http://localhost:8000/user/login
content-type: application/json

{
    "email": "copycat@gmail.com",
    "password": "123"
}
